name: Deploy Next.js site to Ubuntu Server

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build with Next.js
        run: npm run build

      - name: Add SSH Key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}

      - name: Debug SSH Connection
        run: |
          echo "Testing SSH connection..."
          echo "${{ secrets.SERVER_SSH_KEY }}" > private_key
          chmod 600 private_key
          ssh -vvv -i private_key -o StrictHostKeyChecking=no -o ConnectTimeout=60 app@${{ secrets.SERVER_HOST }} echo "SSH connection successful"

      - name: Deploy to server
        if: success()
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /path/to/your/project  # Update this to your actual project path
            git pull origin main
            npm ci
            npm run build
            pm2 restart nextjs-app
